# Generated by Django 3.2 on 2021-06-29 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Architect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='app',
        ),
    ]
